version: '3.7'
services:
  jupyter:
    build: ./
    environment:
      - TZ:Asia/Tokyo
      - JUPYTER_PASSWORD=${JUPYTER_PASSWORD}
    env_file: .env
    volumes:
      - "./notebooks/api:/home/jovyan"
    ports:
      - "8888:8888"
      - "8889:8889"
    container_name: tellus-jupyter

