version: '3.7'
services:
  jupyter:
    build:
      context: .
      dockerfile: Dockerfile.jupyter
    environment:
      - TZ:Asia/Tokyo
      - JUPYTER_PASSWORD=${JUPYTER_PASSWORD}
    env_file: .env
    volumes:
      - "./notebooks/api:/home/jovyan"
    ports:
      - "8888:8888"
    container_name: tellus-jupyter

  kernel_gateway:
    build:
      context: .
      dockerfile: Dockerfile.kernel_gateway
    volumes:
      - "./notebooks/api:/home/jovyan"
    ports:
      - "8889:8889" 
    container_name: kernel_gateway

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80" 
    depends_on:
      - kernel_gateway
    container_name: nginx
