version: '3.7'
services:
  sdav-jupyter:
    build:
      context: ../
      dockerfile: .docker/jupyter.Dockerfile
    environment:
      - TZ:Asia/Tokyo
      - JUPYTER_PASSWORD=${JUPYTER_PASSWORD}
    env_file: .env
    volumes:
      - ../notebooks/api:/home/jovyan
    ports:
      - "8888:8888"
    container_name: tellus-jupyter

  sdav-gateway:
    build:
      context: ../
      dockerfile: .docker/kernel_gateway.Dockerfile
    volumes:
      - ../notebooks/api:/home/jovyan
    ports:
      - "8889:8889"
    container_name: kernel-gateway

  sdav-proxy:
    image: nginx:1.15.8-alpine
    environment:
      LANG: ja_JP.UTF-8
    volumes:
      - ./conf/ssl/50x.html:/usr/share/nginx/html/50x.html
      - ./conf/ssl/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/ssl/default.conf:/etc/nginx/conf.d/default.conf
      - ./wildcard.app.tellusxdp.com.crt:/etc/nginx/wildcard.app.tellusxdp.com.crt
      - ./wildcard.app.tellusxdp.com.key:/etc/nginx/wildcard.app.tellusxdp.com.key
      - ./fake_htpasswd:/etc/nginx/htpasswd
    ports:
      - "80:80"
      - "443:443"
    container_name: sdav-proxy
    links:
      - sdav-gateway

